import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MovieLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en" suppressHydrationWarning>
      
    
            <h1>Hello world</h1>
            {children}
          
      
    </div>
  );
}

